src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UsersRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints\Unique;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity('email', message:"l'email est déja utilisé veuillez vous connectez!")]
#[UniqueEntity('pseudo', message:"le pseudo est deja utilisé")]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[Assert\NotBlank]
    #[Assert\Length(
        min:5,
        max:50,
        minMessage:'le pseudo doit faire minimum 5 charactères',
        maxMessage:'le pseudo ne doit pas dépassé 50 charactères'
    )]
    #[ORM\Column(name:'pseudo', type: 'string', length: 50, unique:true)]
    private $pseudo;
    
    #[Assert\Length(
        max:150,
        maxMessage:'l\'email ne doit pas dépassé 150 charactères'
    )]
    #[Assert\NotBlank]
    #[Assert\Email(message: "l'addresse email n'est pas valide")]
    #[ORM\Column(name:'email', type: 'string', length: 150, unique: true)]
    private $email;

    #[Assert\Length(
        min:8,
        minMessage:'le mot de passe doit faire minimum 8 charactères'
    )]
 
    
    #[ORM\Column(type: 'string', length: 255)]
    private $password;
    
  
    private $confirmPassword;

    #[ORM\Column(type: 'string', length: 255)]
    private $url_img;

    #[ORM\Column(type:"json")]
    private $roles = [];

    #[ORM\OneToMany(mappedBy: 'Users', targetEntity: Articles::class)]
    private $Articles;

    public function __construct()
    {
        $this->Articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    // ajouté pour userinterface
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }


    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getConfirmPassword(): ?string
    {
        return $this->confirmPassword;
    }

    public function setConfirmPassword(string $confirmPassword): self
    {
        $this->confirmPassword = $confirmPassword;

        return $this;
    }

    public function getUrlImg(): ?string
    {
        return $this->url_img;
    }

    public function setUrlImg(string $url_img): self
    {
        $this->url_img = $url_img;

        return $this;
    }

    /**
     * @return Collection|Articles[]
     */
    public function getArticles(): Collection
    {
        return $this->Articles;
    }

    public function addArticle(Articles $article): self
    {
        if (!$this->Articles->contains($article)) {
            $this->Articles[] = $article;
            $article->setUsers($this);
        }

        return $this;
    }

    public function removeArticle(Articles $article): self
    {
        if ($this->Articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getUsers() === $this) {
                $article->setUsers(null);
            }
        }

        return $this;
    }
}

src/Controller/ConnectedController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\ImageType;
use App\Form\SettingInfoType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class ConnectedController extends AbstractController
{

    #[Route('/check', name: 'check')]
    public function check():Response
    {

        if ($this->getUser()->getRoles()[0] === "ROLE_USER") {
            return $this->redirectToRoute('profile', ["id" => $this->getUser()->getId()]);
        } else if ($this->getUser()->getRoles()[0] === "ROLE_ADMIN") {
            return $this->redirectToRoute('admin');
        }
    }


    #[Route('/profile/{id}', name: 'profile')]
    public function index(int $id = null, ManagerRegistry $doctrine): Response
    {

        $userUrl = $doctrine->getRepository(Users::class)->find($id);
        $articles = $userUrl->getArticles()->toArray();
        
        
        return $this->render('connected/index.html.twig', [
            "userUrl" => $userUrl,
            "idParameters" => $id,
            "articles" => $articles
        ]);
    }
   
    #[Route('/setting', name: 'setting')]
    public function setting(): Response
    {
        $user = $this->getUser();
        
        $formImg = $this->createForm(ImageType::class, $user, ["action" => $this->generateUrl('editImg')]);
        $formInfo = $this->createForm(SettingInfoType::class, $user, ["action" => $this->generateUrl('editInfo')]);



        return $this->render('connected/setting.html.twig', [
            'formImg' => $formImg->createView(),
            'formInfo' => $formInfo->createView()
        ]);
    } 
    

    
    

}

templates/connected/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} <link rel="stylesheet" href="/css/profile.css">{% endblock %}

{% block title %}Hello ConnectedController!{% endblock %}

{% block body %}
 
    <div class="container">
        {% if userUrl == null %}
            <h1> l'utilisateur n'existe pas !</h1>

        {% else %}


        <div class="left">

            <img src="/img/{{userUrl.urlImg}}" alt="Image User Profile">

            <div class="info">
                <h3>{{userUrl.pseudo}}</h3>
                <p>Pas De Description</p>
                <p>{{userUrl.email}}</p>
            </div>
        
        </div>
        <div class="right">
            <h1>mes Articles</h1>
            {% if articles %}
                <ul> 
                    {% for article in articles %}
                            
                        <li> {{article.titleArticle}} </li>
                        

                
                    {% endfor %}
                </ul>
            {% else %}
                <h3>Vous N'avez pas creer d'articles</h3>
           
            
             {% endif %}
        
        </div>
        {% endif %}
    
    </div>


{% endblock %}

templates/connected/setting.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} <link rel="stylesheet" href="css/setting.css">{% endblock %}

{% block title %}Parametre de l'utilisateur{% endblock %}

{% block body %}
 
    <div class="container">
        {% for message in app.flashes('succes') %}
            <h3 style="background:green; color:white"> {{ message }} </h3>

        {% endfor %}

        

    <div class="main">

        <div class="editInfo">
            <h1> Modifier les infos</h1>
            {{ form_errors(formInfo) }}
            {{ form(formInfo) }}
        
        </div>

        <div class="editPass">

            <h1>Modifier le mot de passe </h1>
        
            <form action="{{ path('editPassword')}}" method='post'>
        
                <input type="password" placeholder="taper l'ancien mot de passe" name="lastPassword">
                <input type="password" placeholder="nouveau mot de passe" name="newPassword">
                <input type="password" placeholder="confirmer le mot de passe" name="confirmPassword">
                <input type="submit">

            </form>
        </div>

        <div class="editImg">
            <h1>Modifier la photo de profile</h1>

            <div class="infoImg">

                <img src="img/{{app.user.urlImg}}" alt="">

                {{ form(formImg) }}
            </div>
            
        
        </div>

    
    
    </div>
       
        
    
    
    </div>


{% endblock %}

templates/connected/test.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} <link rel="stylesheet" href="css/profile.css">{% endblock %}

{% block title %}Hello ConnectedController!{% endblock %}

{% block body %}
 
    <h1>test</h1>


    {{form(form) }} 

{% endblock %}